create table car(
                    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                    brand varchar,
                    model varchar,
                    price int
);

create table person(
                       id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                       name varchar,
                       age int,
                       has_driver_licence boolean,
                       car int REFERENCES car(id) NOT NULL
);